### ISSUE TITLE
How do I reference a particular table in an article?

### ISSUE THREAD

**Issue by garryde** [trey-wallis/obsidian-dataloom#315]
### Problem

I can't embed a table created with notion-like-tables in a post

### Solution

I can reference a table like a block reference.

**Comment by trey-wallis** [comment]
@garryde Is this possible with the database folder plugin?

**Comment by trey-wallis** [comment]
EDIT: Are you talking about using the ![[My file name]] syntax?

**Comment by piotryordanov** [comment]
@trey-wallis yes, it is possible to use the ![[My File name]] synax to embed a table?

**Comment by DutchPete** [comment]
Same as #345 ?

**Comment by trey-wallis** [comment]
I believe that the purpose of the issue was the ability to embed tables. Please open a new issue if you have any other requests.
