### ISSUE TITLE
Import and export from/to  csv or tsv

### ISSUE THREAD

**Issue by aparente** [trey-wallis/obsidian-dataloom#317]
### Problem

I'd love to be able to import or export a table from/to a csv. I couldn't find anything in the documentation about this so I'm assuming it's not possible yet. 

### Solution

I'm assuming it would be trivial to write a function to transform the data from "|" delimiters to csv or any specified delimiter, but I don't know typescript/js!

**Comment by trey-wallis** [comment]
@aparente Hi aparente. Thanks for your feature request. Yep, that's pretty trivial. Could you give me an example format of how you would like to see your table data? If you look in the table file you will see that it is currently in JSON format. There are 4 different types of entities: column, rows, cells, and tags. Tags are members of a column. Cells are members of a column and row

**Comment by GuybrushX** [comment]
Just a small note in case it's not known already:
Writing a CSV file might sound easy but it's also very easy to mess things up when it comes to exporting quotes or the delimiter or new lines. That needs some special treatment and many tools get this wrong because they don't think about it and are happy to use some "blah.WriteLine()" which isn't enough.

Also how would you export dates and currencies/numbers? Based on the system locale or US only or provide an settings dialog before the export...? Similar with the checkboxes.

I have no idea how this plug-in works or how it is written but if there is a CSV library available I would highly recommend to use that one and check if it can handle such special cases or you'll have to implement everything yourself which isn't that trivial anymore.

Also note that many people say "CSV" but what they mean is "TSV" ;-)

I think there should also be an RFC or another standard which describes and defines the CSV/TSV format in all details with all its pitfalls and how to handle them properly.

**Comment by cesarpereira904** [comment]
First of all congrats fo the amazing work and effort put into this plugin.

I'm not sure if this was the main scenario from the original requester but what I miss is to have the possibility to grab the data on the table and paste it into an Excel sheet / Google sheet. 

For me personally is the only reason I cannot use this plugin at the current moment, to be able to do a copy/paste is a must. 

If to do so I would need to export the table as CVS or TSV, that also would be fine as long I can grab the table contents.

**Comment by MSBack** [comment]
> I'm not sure if this was the main scenario from the original requester but what I miss is to have the possibility to grab the data on the table and paste it into an Excel sheet / Google sheet.

@cesarpereira904 I second this as an additional need. Perhaps you could open a separate issue for selecting and copying from the table?

**Comment by cesarpereira904** [comment]
Issue created : https://github.com/trey-wallis/obsidian-notion-like-tables/issues/452

**Comment by woshitoutouge** [comment]
Very important feature. Imagine someone who has just started using this plugin. He already has some Markdown tables or Excel sheets, but in order to try out this plugin, he has to start building the tables from scratch or copying each cell one by one. This will discourage most people.

**Comment by trey-wallis** [comment]
Added markdown/csv export in 6.13.0

**Comment by pecrazouteisau** [comment]
```
//supported datatypes: text, number, data, multi-tag, tag, number, checkbox
//supported plugin version: 6.17.0
//find and replace all the "\" symbols to "\\" manually in your csv

table_data = ``; //create table and add appropriate number of columns in correct order with correct data-types, paste contents of .table file here

csv_text = ``; //paste your csv
/* example (this is from mysql export btw):
"1";"Text1";"2020-11-26 13:55:20";"tag1,tag2";"singletag0";"0"
"2";"Text2";"2020-11-26 13:56:15";"tag3,tag1";"singletag1";"0"
"4";"Text3.1
Text3.2";"2020-11-26 13:56:30";"tag4";"singletag1";"1" */

entry_delimeter = /^"\d+";/m; 
//you may use '\n' or /^"d+"/m

column_delimeter = '";"';
//you may use ','

tag_delimeter = ','; 
format_dates_to = (d) => {return d.getFullYear()+'/'+(d.getMonth()+1).toString().padStart(2, '0')+'/'+(d.getDate()).toString().padStart(2, '0')};
checkbox_true = '1'; //csv value indicating checkbox is checked

drop_symbols = [1, 2]; //default
//	[amount_of_symbols_to_delete_from_start_of_each_line, amount_of_symbols_to_delete_from_end_of_each_line]
//	example drop_symbols = [0, 0]

drop_symbols_columns = [0, 0]; //default
//	[amount_of_symbols_to_delete_from_start_of_each_column, amount_of_symbols_to_delete_from_end_of_each_column]
//	example drop_symbols_columns = [1, 1]

drop_columns = [1, 2]; //default
//	order of remained columns changes after dropping, note that in reorder_columns
//	example drop_columns = [] 

reorder_columns = {}; //default
//example reorder_columns = {0: 2, 2: 0}
//untested lol

filter_rows = (row) => {if (row.length == 1 && row[0] == '') return true}; //if returns true - row gets deleted

table_data = JSON.parse(table_data.replace(/\n[\s\t]+/g, ''));

csv_data = csv_text.replace(/;"N/g, ';""').split(entry_delimeter);

for (const line in csv_data) {
	csv_data[line] = csv_data[line].substr(drop_symbols[0], (csv_data[line].length - drop_symbols[0] - drop_symbols[1])).split(column_delimeter);
	
	if (drop_columns.length > 0){
		for (const column of drop_columns) {
			delete csv_data[line][column];
		};
		csv_data[line] = csv_data[line].flat();
	};

	for (const column in csv_data[line]) {
		csv_data[line][column] = csv_data[line][column].substr(drop_symbols_columns[0], (csv_data[line][column].length - drop_symbols_columns[0] - drop_symbols_columns[1]));
	};

	if (Object.keys(reorder_columns).length > 0){
		for (column_old_placing in Object.keys(reorder_columns)){
			column = csv_data[line][column_old_placing];
			csv_data[line].splice(column_old_placing, 1);
			csv_data[line].splice(reorder_columns[column_old_placing], 0, column);
		};
	};
};

for (const line in csv_data) {
	if (filter_rows(csv_data[line])){
		csv_data.splice(line, 1);
	};
};

entries_length_stats = {};
for (const line of csv_data) {
	entries_length_stats[line.length] = (typeof entries_length_stats[line.length] != 'undefined') ? entries_length_stats[line.length]+1 : 1;
};
console.log(csv_data);
console.log(entries_length_stats);

if (confirm(`Console looks good?`)){
	for (const data of csv_data) {
		add_line(data);
	};
	console.log(JSON.stringify(table_data, null, 2));
} else {
	console.log('better luck next time');
};

//thx: https://stackoverflow.com/a/2117523
function uuidv4() {
	return ([1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, c =>
	  (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
	);
}  


function add_line(data){
	new_row_uuid = uuidv4();
	table_data.model.bodyRows.push({
		creationTime: (new Date()).getTime(),
		lastEditedTime: (new Date()).getTime(),
		id: new_row_uuid,
		index: (table_data.model.bodyRows.length > 0) ? (table_data.model.bodyRows[table_data.model.bodyRows.length - 1].index + 1) : 0
	});
	for (const column in data) {
		if (table_data.model.columns.length > column){
			if (table_data.model.columns[column].type == 'date'){
				if (!isNaN((new Date(data[column])).getTime())){
					table_data.model.bodyCells.push({
						id: uuidv4(),
						columnId: table_data.model.columns[column].id,
						rowId: new_row_uuid,
						tagIds: [],
						dateTime: new Date(data[column]).getTime(),
						markdown: format_dates_to(new Date(data[column]))
					});
				} else {
					console.log('failed to parse date '+data[column]);
					table_data.model.bodyCells.push({
						id: uuidv4(),
						columnId: table_data.model.columns[column].id,
						rowId: new_row_uuid,
						tagIds: [],
						dateTime: (new Date()).getTime(),
						markdown: format_dates_to(new Date())
					});
				};
			} else if (table_data.model.columns[column].type == 'multi-tag'){
				local_cell_data = data[column].split(tag_delimeter);
				tagIds = [];
				local_cell_data.map(tag => {
					tag_already_exists = false;
					table_data.model.columns[column].tags.map(existing_tag => {
						if (existing_tag.markdown == tag){
							tag_already_exists = true;
							tag_uuid = existing_tag.id;
						};
					});
					if (!tag_already_exists){
						tag_uuid = uuidv4();
						table_data.model.columns[column].tags.push({
							id: tag_uuid,
							markdown: tag,
							color: ["light gray", "gray", "brown", "orange", "yellow", "green", "blue", "purple", "pink", "red"][Math.ceil(Math.random()*10)]
						});
					};
					tagIds.push(tag_uuid);
				});
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[column].id,
					rowId: new_row_uuid,
					tagIds: tagIds,
					dateTime: null,
					markdown: data[column]
				});
			} else if (table_data.model.columns[column].type == 'tag'){
				tagIds = [];
				[data[column]].map(tag => {
					tag_already_exists = false;
					table_data.model.columns[column].tags.map(existing_tag => {
						if (existing_tag.markdown == tag){
							tag_already_exists = true;
							tag_uuid = existing_tag.id;
						};
					});
					if (!tag_already_exists){
						tag_uuid = uuidv4();
						table_data.model.columns[column].tags.push({
							id: tag_uuid,
							markdown: tag,
							color: ["light gray", "gray", "brown", "orange", "yellow", "green", "blue", "purple", "pink", "red"][Math.ceil(Math.random()*10)]
						});
					};
					tagIds.push(tag_uuid);
				});
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[column].id,
					rowId: new_row_uuid,
					tagIds: tagIds,
					dateTime: null,
					markdown: data[column]
				});
			} else if (table_data.model.columns[column].type == 'text' || table_data.model.columns[column].type == 'number'){
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[column].id,
					rowId: new_row_uuid,
					tagIds: [],
					dateTime: null,
					markdown: data[column]
				});
			} else if (table_data.model.columns[column].type == 'checkbox'){
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[column].id,
					rowId: new_row_uuid,
					tagIds: [],
					dateTime: null,
					markdown: (data[column] == checkbox_true) ? '[x]' : '[ ]'
				});
			};
		} else {
			console.log('column overflow: '+column+', data: '+data[column]+'row: ', data);
		};
	};

	if (data.length < table_data.model.columns.length){
		for (let i = 1; i <= (table_data.model.columns.length - data.length); i++) {
			if (table_data.model.columns[data.length + i - 1].type == 'date'){
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[data.length + i - 1].id,
					rowId: new_row_uuid,
					tagIds: [],
					dateTime: (new Date()).getTime(),
					markdown: format_dates_to(new Date())
				});
			} else if (table_data.model.columns[data.length + i - 1].type == 'multi-tag' || table_data.model.columns[data.length + i - 1].type == 'tag'){
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[data.length + i - 1].id,
					rowId: new_row_uuid,
					tagIds: [],
					dateTime: null,
					markdown: ""
				});
			} else if (table_data.model.columns[data.length + i - 1].type == 'text'){
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[data.length + i - 1].id,
					rowId: new_row_uuid,
					tagIds: [],
					dateTime: null,
					markdown: ""
				});
			} else if (table_data.model.columns[data.length + i - 1].type == 'number'){
				table_data.model.bodyCells.push({
					id: uuidv4(),
					columnId: table_data.model.columns[data.length + i - 1].id,
					rowId: new_row_uuid,
					tagIds: [],
					dateTime: null,
					markdown: ""
				});
			};
		};
	};
};

```

Public domain or something. This is temporary account and I will not respond.

**Comment by marvinvr** [comment]
Hey @trey-wallis!

First of all, I really like the idea of your plugin! It would really be a great addition to it, maybe as an optional way to store the data. I'd imagine having a CSV file with all the Data and then a separate Metadata JSON file, which would be a really elegant way to store the data without relying on Obsidian (or this plugin), whilst keeping all the “notion-like” functionality in the for the user.

I have a few years of experience working on Typescript projects with Redux, some TSX experience, but nothing specific in regard to react or obsidian. 

I would really like to help with this, would you be open to collaborating with this feature?

**Comment by gustavosr98** [comment]
I love this plugin
I am eager to start importing my existing tables into this format

Is this currently WIP?

**Comment by yyusufcoskun** [comment]
Hi, any updates? I have tons of Notion databases I want to carry over to Obsidian, and I really don't want to copy paste them 1 by 1.

I'm not sure if this is what's been talked about but splitting columns by the delimiter seems to be the easiest solution to this. I'm not sure though.

**Comment by trey-wallis** [comment]
> Hey @trey-wallis!
> 
> First of all, I really like the idea of your plugin! It would really be a great addition to it, maybe as an optional way to store the data. I'd imagine having a CSV file with all the Data and then a separate Metadata JSON file, which would be a really elegant way to store the data without relying on Obsidian (or this plugin), whilst keeping all the “notion-like” functionality in the for the user.
> 
> I have a few years of experience working on Typescript projects with Redux, some TSX experience, but nothing specific in regard to react or obsidian.
> 
> I would really like to help with this, would you be open to collaborating with this feature?

Could you explain the metadata JSON file? I don't understand what that would be.

**Comment by trey-wallis** [comment]
@gustavosr98 @yyusufcoskun Will be pushing out an update later today :)

**Comment by yyusufcoskun** [comment]
@trey-wallis Hi! I've updated the plugin but couldn't seem to find how to do it. Is it just the **exporting** part that's been done for now? Or am I just missing the import button?

Either way, great work!

**Comment by FeralFlora** [comment]
> @trey-wallis Hi! I've updated the plugin but couldn't seem to find how to do it.

The update @trey-wallis mentioned hasn't been released yet

**Comment by yyusufcoskun** [comment]
> > @trey-wallis Hi! I've updated the plugin but couldn't seem to find how to do it.
> 
> The update @trey-wallis mentioned hasn't been released yet

Oh, I'm sorry I didn't realize, how do you access this information? I'm really curious, I'm new to all this that's why I'm asking

**Comment by FeralFlora** [comment]
> Oh, I'm sorry I didn't realize, how do you access this information? I'm really curious, I'm new to all this that's why I'm asking

No worries!

You can keep an eye out on the Release page: https://github.com/trey-wallis/obsidian-dataloom/releases or even subscribe to notifications upon new releases on the main Dataloom repo page using the bell icon.

I happen to know that the latest releases version was 8.2.2 when @trey-wallis wrote the message above, so the import feature will be in a version above that.

Also, you can look at the changelog for each release to see what's new. Usually, issues will be linked in the changelog, so those links will appear as backlinks in the relevant issue being addressed / resolved.

**Comment by yyusufcoskun** [comment]
@FeralFlora Thanks!

**Comment by trey-wallis** [comment]
> @gustavosr98 @yyusufcoskun Will be pushing out an update later today :)

Sorry. I posted that messaged and then had some things come up. I also have decided to spend some additional time developing this feature since it is one of the most important features of the plugin. The update is almost ready.

**Comment by yyusufcoskun** [comment]
> > @gustavosr98 @yyusufcoskun Will be pushing out an update later today :)
> 
> Sorry. I posted that messaged and then had some things come up. I also have decided to spend some additional time developing this feature since it is one of the most important features of the plugin. The update is almost ready.
> 

No worries! As I said I wasn't aware of how to check the new releases. And I think you've made the right call with delaying deployment, may it be easy on you

**Comment by gustavosr98** [comment]
Thanks @trey-wallis,

I am more than happy to help you develop this plugin
We can take it offline to discuss how I or anyone else can help on this

**Comment by trey-wallis** [comment]
@aparente @GuybrushX @FeralFlora @marvinvr @gustavosr98 @yyusufcoskun @woshitoutouge @cesarpereira904 Added CSV/markdown import in 8.3.0.

Please see: https://dataloom.xyz/other/import for instructions

**Comment by trey-wallis** [comment]
I plan on closing this issue for now. If anyone needs TSV importing/exporting please open another issue. Thanks :)
