### ISSUE TITLE
Two columns sorting

### ISSUE THREAD

**Issue by vratclarkson** [trey-wallis/obsidian-dataloom#318]
### Problem

Hello there, 
Thank you developing this plugin. 
It is simple and elegant. 

I was wondering, if it possible for you to develop sorting two columns, like, in Notion. 
For example Date and Priority

### Solution

I am not a programmer so... No idea how to do this.

**Comment by trey-wallis** [comment]
Hey. I appreciate your feature request. The current behavior of sorting in Notion is if you click "Ascending" or "Descending" on any column, it will sort by that column. If you already have a column that you are sorting by, it will replace that sorted column with the new column. If you wish to sort by multiple columns, you have to go into another menu. 

How would you rate Notion's current functionality of column sorting? Does it make sense to override the sorted column if you click "Ascending" or "Descending"? 

Another option that I would propose would be to make it multiple sort by default.

Example:
- Sorting by nothing
- **Click ascending on column 1**
- Sorting by column 1
- **Click descending on column 2**
- Sorting by column 1 and then column 2

The filters would appear and could be removed by the user or reorganized.

**Comment by vratclarkson** [comment]
It doesn't make sense to override already sorted columns. 
Thanks for the great work.

**Comment by trey-wallis** [comment]
Added in 8.2.0.
