### ISSUE TITLE
Add support for the ISO 8601 YYYY-MM-DD date format

### ISSUE THREAD

**Issue by sebdanielsson** [trey-wallis/obsidian-dataloom#414]
### Problem

As a swedish user it feels weird to not enter the date in our official date and time format. (ISO 8601)

Support for this date and time format would be much appreciated.

### Solution

Implement support for ISO 8601 date and time format.
https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by sebdanielsson** [comment]
To make the date and times more flexible for future regional standards maybe something like Moment.js could be used?

https://momentjs.com

**Comment by sebdanielsson** [comment]
Day.js is 2 KB and is mostly compatible with the well known Moment.js.

It would also allow for easy calculation for full and relative dates in all imported date and time formats.

https://www.npmjs.com/package/dayjs

**Comment by trey-wallis** [comment]
@sebdanielsson The table currently supports `YYYY/MM/DD`


https://user-images.githubusercontent.com/40307803/236889118-da9e28be-32c6-4a06-926a-027c2b27f3de.mov

**Comment by trey-wallis** [comment]
I can make a "default date format" option though and place it in the settings. The international library is a good idea as well.

**Comment by sebdanielsson** [comment]
Hi, thank you for the quick response! In Sweden we separate year, month, day with - and not /. The library would take care of suck details as well🤩

**Comment by trey-wallis** [comment]
Oh gotcha. That is good to know! Does using `Day.js` automatically account for your location or would a user still need to specify their localization?

**Comment by putzwasser** [comment]
I'd like to contribute another idea: Please support time, too. Maybe create two more data fields:
- time and
- datetime
OR combine all three in the existing one.

> My guess is that the easiest implementation would be to store all dates and times in ISO format and then convert the dates before displaying them
I feel like this is the common approach to dates. It would be best to convert them once to ISO, store them in ISO format and output it either
- via a user format setting (like for daily notes titles, etc.)
- via the locale
- or as ISO string as fallback.

**Comment by trey-wallis** [comment]
@sebdanielsson Added in 8.12.0
