### ISSUE TITLE
Using Windows Key + . to insert an emoji doubles the emoji in the cell

### ISSUE THREAD

**Issue by GuybrushX** [trey-wallis/obsidian-dataloom#425]
### Describe the bug

See title

### Steps to reproduce

See title

### Expected behavior

Emoji should be added only once.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.2.7
	Installer version: v1.2.7
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 10
		1: Obsidian Git v2.19.1
		2: Calendar v1.5.10
		3: Tasks v3.5.0
		4: Dataview v0.5.55
		5: Excalidraw v1.8.26
		6: ExcaliBrain v0.1.13
		7: Kanban v1.5.3
		8: Natural Language Dates v0.6.1
		9: Advanced Tables v0.18.1
		10: Notion-Like Tables v6.8.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@GuybrushX Could I get a video of this? I primarily develop on a Mac computer

**Comment by trey-wallis** [comment]
Fixed in 8.1.0
