### ISSUE TITLE
Insert above, insert below

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-dataloom#445]
### Problem

Even though a user has the ability to drag and drop, if someone has > 50 rows, it's very tedious to drag rows from the bottom to the top

### Solution

Add a insert above, insert below for rows

**Comment by trey-wallis** [comment]
https://github.com/trey-wallis/obsidian-notion-like-tables/issues/434#issuecomment-1553719720

**Comment by lymeswold** [comment]
Hi Trey, we *need* this feature (preferably for both rows AND columns)!! Would like to suggest that it's a *high priority* enhancement. Thanks.

**Comment by trey-wallis** [comment]
@lymeswold @feralflora. Added in 8.2.0.
