### ISSUE TITLE
I don’t see any import modal

### ISSUE THREAD

**Issue by csss1234** [trey-wallis/obsidian-dataloom#456]
### Describe the bug

It’s mentioned in the readme. Is there a simple way to convert existing pipe tables to Notion like tables?

### Steps to reproduce

.

### Expected behavior

.

### Are you using the mobile app?

No

### Obsidian debug info

.

**Comment by csss1234** [comment]
Found. Would be nice if it was in command pallets or right click

**Comment by trey-wallis** [comment]
Hi @csss1234. No, this is not currently a feature. Right now you can only convert markdown lists to rows in a table.

```markdown
- bullet 1
- bullet 2
- bullet 3
```

**Comment by BobWs** [comment]
This happens when importing MD list into table (see screenshot)
![Screen_Shot](https://github.com/trey-wallis/obsidian-notion-like-tables/assets/5485820/00df1ce0-9dd9-430a-b730-550fcfd01fff)

**Comment by trey-wallis** [comment]
@BobWs Can you select the first column as you target when importing?

**Comment by BobWs** [comment]
> @BobWs Can you select the first column as you target when importing?

I selected to first kolom and then imported the first list, that went into the first kolom as you can see on the sreenshot, and then I imported the second list into the second kolom and than it imported everything as you can see in the kolom way below...

**Comment by trey-wallis** [comment]
@BobWs Ah, I see what you mean now. I will need to upgrade the import system to be able to handle more complexity

**Comment by BobWs** [comment]
> I see what you mean now. I will need to upgrade the import system to be able to handle more complexity

Thank you! Looking forward to the next update...

**Comment by Barthcbb** [comment]
> Hi @csss1234. No, this is not currently a feature. Right now you can only convert markdown lists to rows in a table.
> 
> ```gfm
> - bullet 1
> - bullet 2
> - bullet 3
> ```

Hi @trey-wallis, what should one do with that md list to make it into rows?
When I paste that sample snippet I get a markdown list inside the column.

**Comment by trey-wallis** [comment]
@Barthcbb I have temporarily disabled importing until I design a better system

**Comment by wuye9036** [comment]
So any update?

**Comment by trey-wallis** [comment]
Importing via markdown tables and CSV added in 8.3.0. Please see: https://dataloom.xyz/other/import
