### ISSUE TITLE
Add support for embedded tables in reading mode

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-dataloom#513]
### Problem

Add support for an embedded table in preview mode

### Solution

use the `MarkdownPostProcessor` function

**Comment by qianlifeng** [comment]
Currently, I can edit the table in preview mode, it should be unchangeable

**Comment by Pachtjuilaard** [comment]
I would actually prefer the table to be editable in preview mode. Maybe using a toggle for allowing/disallowing editing in preview mode would be handy.

**Comment by trey-wallis** [comment]
Added in 8.1.0
