### ISSUE TITLE
Mobile is really laggy

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-dataloom#515]
### Describe the bug

Mobile is so laggy it's unusable.

### Steps to reproduce

Type in any menu input. It will lag very badly.

### Expected behavior

No lag.

### Are you using the mobile app?

Yes

### Obsidian debug info

N/A

**Comment by trey-wallis** [comment]
@compg Are you having any problems with lagginess on mobile?

**Comment by trey-wallis** [comment]
Resolved a majority of the input lag. The table needs to optimized though.

**Comment by Compg** [comment]
> @Compg Are you having any problems with lagginess on mobile?

Hadn’t tested further after reinstall. Seems to be working as expected in latest release.

**Comment by MSBack** [comment]
Mobile is okay for me, but it is very difficult to drag a column to reorder, as the whole loom gets dragged instead.
