### ISSUE TITLE
Inputing a Chinese comma，it will be insert doubles the comma in the cell

### ISSUE THREAD

**Issue by linseyyu** [trey-wallis/obsidian-dataloom#522]
### Describe the bug

When i input a Chinese comma，it will be insert two automatically，but if i input a english comma，it just be one.

### Steps to reproduce

When i input a Chinese comma，it will be insert two automatically.
Like input “，”，will insert “，，”

### Expected behavior

The comma should be added only once.

### Are you using the mobile app?

No

### Obsidian debug info

/

### Relevant log output

```shell
/
```

**Comment by Quorafind** [comment]
Cannot repro

**Comment by trey-wallis** [comment]
I believe that this was fixed a while ago. Related to #425
