### ISSUE TITLE
Embedded table link is rendered in reading view

### ISSUE THREAD

**Issue by 30756454** [trey-wallis/obsidian-dataloom#530]
### Describe the bug

Embedded table link can be rendered in editing view. But in reading view,it just show a button which link to the `.table`file.

### Steps to reproduce

1. Creat embedded table link by using syntax `![[filename.table]]` in a `.md` file.
2. Switch the `.md` file to reading view.
3. NTL do not show in reading view.

### Expected behavior

NTL shows the same way as editing view

### Are you using the mobile app?

No

### Obsidian debug info

N/A

### Relevant log output

```shell
No Response
```

**Comment by trey-wallis** [comment]
Related to #513

**Comment by trey-wallis** [comment]
Fixed in 8.1.0
