### ISSUE TITLE
Exceed width in edit mode

### ISSUE THREAD

**Issue by guofei1989** [trey-wallis/obsidian-dataloom#564]
### Problem

When the number of columns in the table is excessive or the width exceeds the limit, it becomes difficult to edit.

### Solution

Is is feasible to drag and drop different positions of the table?

**Comment by trey-wallis** [comment]
Hi @guofei1989. Could you give me a screen? What do you mean by it becomes difficult to edit?

Yes, you can drag and drop either columns or rows.

**Comment by trey-wallis** [comment]
Test
