### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by stoweboyd** [trey-wallis/obsidian-dataloom#576]
### Problem

I would like to set reminders on rows in a NLT.

### Solution

The reminders plug in accepts Kanban and calendar style date formats. Should be an option for date fields to type in one or the other of these.

### Additional details

Date fields in NLTs are not standard format: 2023-06-20. This should be an option.

**Comment by trey-wallis** [comment]
@stoweboyd. 8.14.0 has support for various date formats, including the format you have specified. Please check it out :)
