### ISSUE TITLE
Multi-Select to stay open until all options are selected

### ISSUE THREAD

**Issue by ThisIsKeb** [trey-wallis/obsidian-dataloom#618]
### Problem

When using a multi-select column, you need to click on the cell and open the drop-down to add in each selection individually. 

### Solution

It would be a large quality of life improvement to leave the dropdown for the multi-select open until you have selected all the options you wanted for that section, so that you don't need to keep clicking back into it.

**Comment by trey-wallis** [comment]
Added in 8.1.0.
