### ISSUE TITLE
Add ability to "freeze" colums so they stay visible while scrolling

### ISSUE THREAD

**Issue by FeralFlora** [trey-wallis/obsidian-dataloom#631]
### Problem

When sidescrolling in looms with many columns, it is hard to tell which row you are looking at. It becomes necessary to scroll back and forth before editing, which is tedious.

### Solution

Add the ability to pin or "freeze" the first X number of columns so that they always stay in view while side-scrolling. 

Freezing the first column would be sufficient, although the ability to freeze more might be convenient too.

### Additional details

Excel has this feature, for reference: https://support.microsoft.com/en-au/office/freeze-panes-to-lock-rows-and-columns-dab2ffc9-020d-4026-8121-67dd25f2508f

**Comment by trey-wallis** [comment]
I like this suggestion. This should be very easily to implement.

**Comment by trey-wallis** [comment]
Added in 8.2.0.
