### ISSUE TITLE
Support time in date field

### ISSUE THREAD

**Issue by cmd410** [trey-wallis/obsidian-dataloom#633]
### Problem

Sometimes there's a need to store time along with date, yet date field doens't support this and there's not dedicated field for time.

### Solution

Implement optional time part of date field. The format could be:

- `2023/07/14 23:09`
- `2023/07/14 11:09 PM`

**Comment by simonfossom** [comment]
This is very much needed...

**Comment by trey-wallis** [comment]
@cmd410 @simonfossom Added in 8.12.0
