### ISSUE TITLE
Custom number formats

### ISSUE THREAD

**Issue by Flavinsh** [trey-wallis/obsidian-dataloom#636]
### Problem

Currently, it is not possible to specify number format, e.g. units, when the _Number_ data type is chosen. 
This is also a problem in Notion, but I guess it might be relatively easy to implement.

At the moment, users have to chose either to:
- use _Number_ format (but without any formatting / units, making data harder to read at a glance)
- use _Text_ format and manually specifying units (but lose _Number_ capabilities, e.g. sum / average / min / max, etc) 

### Solution

**Add the ability to specify a customised number format**, similarly to Microsoft Excel.
_Example_:
- Currencies: $, €, ...
- Units: kg, km/h, m, hp, Nm, °C, etc

This feature would make databases with factual, number-based data much more readable, while preserving the current features of _Number_ data (incl. computations).

**Comment by trey-wallis** [comment]
Added in 8.5.0 :)

Thanks to @roman-balzer
