### ISSUE TITLE
Sorting by multiple criteria does not work

### ISSUE THREAD

**Issue by Zachary0116** [trey-wallis/obsidian-dataloom#637]
### Describe the bug

![Screenshot 2023-07-19 at 14 52 48](https://github.com/trey-wallis/obsidian-dataloom/assets/139985852/411415ff-642e-4c58-9d61-00d58bbcebfb)

Sorting only works when it is by one criterion only

### Steps to reproduce

/

### Expected behavior

/

### Are you using the mobile app?

No

### Obsidian debug info

/

**Comment by trey-wallis** [comment]
Hi @Zachary0116. Yes, this is a known bug. I will fix it this week.

Related to #318

**Comment by trey-wallis** [comment]
Fixed in 8.2.0.
