### ISSUE TITLE
Title won't change if options menu is closed by changing type

### ISSUE THREAD

**Issue by 42ama** [trey-wallis/obsidian-dataloom#641]
### Describe the bug

Title won't change if options menu is closed by changing type. Guess that changing column type won't trigger save of all updated “column view” and only saves updated icon for type.

### Steps to reproduce

1. Create new embedded dataloom. 
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/d49ad192-5ca4-4101-a6b7-096c0a5f58f2)
2. Change column name.
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/5cc6bb30-2391-43f0-affb-bc704d609545)
3. Change type.
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/e4c4105b-444b-4f5c-b12d-87e3baea2ab2)
**Result**: Type changed, while column name isn't.
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/b758c0d0-08b2-4f16-9e97-b59d1cba0deb)

If I open column settings again and press Enter – title updates.
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/30d745b4-a0ff-4741-abf2-a0cace89d23a)

### Expected behavior

After column settings menu is disappeared – column name is displayed changed.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.19042
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 16
	Plugins enabled: 15
		1: Templater v1.16.0
		2: TagFolder v0.16.5
		3: Excalidraw v1.9.8
		4: Dataview v0.5.56
		5: Advanced Tables v0.18.1
		6: Periodic Notes v0.0.17
		7: Rollover Daily Todos v1.1.6
		8: Admonition v9.3.3
		9: Obsidian Git v2.20.6
		10: Emoji Toolbar v0.4.1
		11: DataLoom v8.0.0
		12: Calendar v1.5.10
		13: Underline v1.2.1
		14: Language Translator v1.0.3
		15: Surfing v0.8.16

**Comment by trey-wallis** [comment]
@42ama Thanks for finding this. This was a very specific bug. I appreciate all your testing.

**Comment by trey-wallis** [comment]
Fixed in 8.11.3
