### ISSUE TITLE
There is no scroll bar???

### ISSUE THREAD

**Issue by SomethingShard** [trey-wallis/obsidian-dataloom#645]
### Describe the bug

Hello, So, when you create a lot of Entries, and then go to toggles, there is no scroll bar.
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/90984893/c71efe26-7001-4968-939f-d122541b062d)

### Steps to reproduce

Create alot of Entries, and then try to reach older ones, they go off the screen and as far as i can tell, are inaccessable

### Expected behavior

I thought there would maybe be a scroll bar, but to be fair, it probably wasnt expected a use case

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.5
	Installer version: v1.1.16
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Minimal v6.3.2
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 10
	Plugins enabled: 9
		1: Minimal Theme Settings v6.3.2
		2: Tag Wrangler v0.5.11
		3: TagFolder v0.16.9
		4: Emoji Toolbar v0.4.1
		5: DataLoom v8.0.0
		6: Highlightr v1.2.2
		7: Style Settings v1.0.6
		8: Jelly Snippets v0.1.5
		9: Table Generator v1.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
There isnt, really, any relevant log Input???
```

**Comment by trey-wallis** [comment]
Yep, it wasn't an expected case. It will be added shortly. Thanks for the bug report
