### ISSUE TITLE
Allow multiple lines with ALT+ENTER

### ISSUE THREAD

**Issue by Citatap** [trey-wallis/obsidian-dataloom#647]
### Problem

The only way to implement multiple lines in a cell is shift + enter.
If alt + enter is also available, it seems to be more convenient to write down texts.

### Solution

Allow multiple lines with ALT+ENTER

**Comment by trey-wallis** [comment]
Hi @Citatap. Thank you for your feature request. I will add this today

**Comment by trey-wallis** [comment]
After doing a little research, it appears that `alt` is not usually a key used for inserting new lines on the web. I cannot

**Comment by trey-wallis** [comment]
Edit: It seems like Google sheets doesn't support shift and uses alt instead which is really interesting.

**Comment by trey-wallis** [comment]
Added in 8.2.2
