### ISSUE TITLE
Mobile. Opened loom table will shrink after any action

### ISSUE THREAD

**Issue by 42ama** [trey-wallis/obsidian-dataloom#649]
### Describe the bug

When you inside in loom file and open another tab or shrink/open app - loom table will collapse.

### Steps to reproduce

1. Open loom file (not embeded).
2. Slide to the settings OR shrink/open app.
Actual behavior: Loom table will shrink with no possibilities to write in it.

Video with bug reproduce steps:
https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/187e790e-3d54-47d0-8b1d-529748715867

### Expected behavior

Loom table won't shrink and stay the same.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
 Operating system: ios 14.6 (Apple iPhone)
 Obsidian version: 1.4.6 (105)
 API version: v1.3.5
 Login status: not logged in
 Live preview: on
 Legacy editor: off
 Base theme: dark
 Community theme: none
 Snippets enabled: 0
 Restricted mode: off
 Plugins installed: 4
 Plugins enabled: 3
  1: Obsidian Git v2.20.6
  2: DataLoom v8.0.0
  3: TagFolder v0.16.9

**Comment by trey-wallis** [comment]
@42ama Is this happening in 8.1.0?

**Comment by 42ama** [comment]
No, in 8.1.0 it was fixed. Thanks
