### ISSUE TITLE
Dataloom reverts from 8.0.0 to 6.19.1 every time I restart the Obsidian app

### ISSUE THREAD

**Issue by MSBack** [trey-wallis/obsidian-dataloom#653]
### Describe the bug

After updating to Dataloom 8.0.0, every time I close and reopen the Obsidian app, Dataloom will have reverted to version 6.19.1, thus becoming "Dashboards" again. This makes me unable to open my Looms until I update to version 8.0.0 again.

### Steps to reproduce

Install or update to version 8.0.0 of Dataloom. Restart Obsidian and check the plugin version.

### Expected behavior

I would expect Dataloom updates to stay persistent, and not downgrade all the way to version 6.19.1.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Operating system: ios 16.5.1 (Apple iPad)
	Obsidian version: 1.4.6 (105)
	API version: v1.3.5
	Login status: logged in
	Catalyst license: insider
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Aura v2.0.0
	Snippets enabled: 7
	Restricted mode: off
	Plugins installed: 48
	Plugins enabled: 47
		1: Kanban v1.5.3
		2: Tasks v4.4.0
		3: Dataview v0.5.56
		4: Calendar v1.5.10
		5: Homepage v3.3.3
		6: Templater v1.16.0
		7: Excalidraw v1.9.12
		8: Enhancing Mindmap v0.2.4
		9: Periodic Notes v0.0.17
		10: Projects v1.16.3
		11: Home tab v1.1.2
		12: Force note view mode v1.2.0
		13: Obsidian42 - Text Transporter v1.0.3
		14: Obsidian42 - Strange New Worlds (SNW) v1.2.2
		15: Obsidian42 - BRAT v0.7.0
		16: Buttons v0.4.19
		17: Hotkeys++ v0.2.7
		18: Outliner v4.8.0
		19: QuickAdd v1.2.1
		20: Style Settings v1.0.6
		21: Emoji Toolbar v0.4.1
		22: Natural Language Dates v0.6.1
		23: Advanced new file v1.5.1
		24: Commander v0.5.0
		25: Linter v1.18.0
		26: Auto Link Title v1.4.1
		27: txt as md v0.0.1
		28: qmd as md v0.0.2
		29: Hover Editor v0.11.13
		30: List Callouts v1.1.4
		31: LanguageTool Integration v0.3.4
		32: Simple Day Planner v0.2.0
		33: Dictionary v2.22.0
		34: Rollover Daily Todos v1.1.6
		35: Markdown Table Editor v0.3.1
		36: Numerals v1.2.0
		37: Tag Wrangler v0.5.11
		38: Novel word count v2.17.1
		39: Lapel v0.1.1
		40: Various Complements v8.3.2
		41: Dashboards v6.19.1
		42: Supercharged Links v0.9.7
		43: QuickShare v1.3.1
		44: Emoji Shortcodes v2.2.0
		45: Banners v1.3.3
		46: Full Calendar v0.10.7
		47: Better Word Count v0.10.0

**Comment by trey-wallis** [comment]
@MSBack I'm sorry that is happening. It is clearly unintended. Will look into it and add it to the next release in the next hour

**Comment by trey-wallis** [comment]
For clarification, your `.table` or `.dashboard` files were updated to `.loom` and then it's just the plugin that is reverting back to 6.19.1?

**Comment by trey-wallis** [comment]
Could you also examine `<your-vault>/.obsidian/plugins`. Do you have a `notion-like-tables` folder? When you go inside of it, what does the `manifest.json` file say?

**Comment by MSBack** [comment]
> For clarification, your `.table` or `.dashboard` files were updated to `.loom` and then it's just the plugin that is reverting back to 6.19.1?

Yes, exactly.

**Comment by MSBack** [comment]
> Could you also examine `<your-vault>/.obsidian/plugins` folder. Is there a `notion-like-tables` folder? When you go inside of it, what does the `manifest.json` file say?

Yes, there is both a `notion-like-tables` folder and a obsidian-dashboards-6.19.1 folder. The `notion-like-tables` manifest says:

```
{
	"id": "notion-like-tables",
	"name": "DataLoom",
	"minAppVersion": "1.2.0",
	"description": "Weave together data from diverse sources into a cohesive table view. Inspired by Excel Spreadsheets and Notion.so.",
	"author": "Trey Wallis",
	"authorUrl": "https://github.com/trey-wallis",
	"isDesktopOnly": false,
	"fundingUrl": "https://www.buymeacoffee.com/treywallis",
	"version": "8.0.0"
}
```

**Comment by trey-wallis** [comment]
Yep, that's what I was thinking. The only way for this to happen would be
if there were actually had 2 different versions of a plugin with the same
id installed. Can you delete the dashboards folder? That should solve the
issue

**Comment by MSBack** [comment]
Thanks, that was indeed the issue. Not sure how I ended up with two versions, though. I didn´t do a manual install. Perhaps I missed a previous install due to the rebrand?
