### ISSUE TITLE
No horizontal scrollbar (on desktop)

### ISSUE THREAD

**Issue by gernalix** [trey-wallis/obsidian-dataloom#660]
### Describe the bug

DataLoom on Obsidian desktop cuts tables with too many columns instead of showing a horizontal scrollbar to view all of the columns.

![image](https://github.com/trey-wallis/obsidian-dataloom/assets/22417984/008bfe8d-a42f-450c-bf95-8807bd1a0bfa)

### Steps to reproduce

Create a loom with a number of columns that doesn't fit in the screen

### Expected behavior

A horizontal scrollbar should appear to scroll through all the columns

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.2
	Installer version: v1.3.5
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.1.1
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 101
	Plugins enabled: 34
		1: Divide & Conquer v1.0.0
		2: Lumberjack 🪓 🪵 v1.3.0
		3: Mousewheel Image zoom v1.0.19
		4: Natural Language Dates v0.6.1
		5: DataLoom v8.1.0
		6: Obsidian Enhancing Export v1.8.4
		7: Omnisearch v1.15.2
		8: Pandoc Plugin v0.4.1
		9: Quick Switcher++ v3.3.5
		10: QuickAdd v1.2.1
		11: Recent Files v1.3.7
		12: Style Settings v1.0.6
		13: Table Generator v1.3.1
		14: Outliner v4.8.0
		15: Heading Level Indent v1.0.3
		16: Emoji Titler v1.0.4
		17: Annotator v0.2.10
		18: Journal Review v1.0.4
		19: Excel to Markdown Table v0.4.0
		20: ExcaliBrain v0.2.6
		21: Dataview v0.5.56
		22: Imgur Plugin v2.2.1
		23: Excalidraw v1.9.12
		24: Settings Search v1.3.8
		25: Minimal Theme Settings v6.3.2
		26: Contextual Typography v2.2.5
		27: Highlightr v1.2.2
		28: Auto Link Title v1.4.1
		29: Global Hotkeys v0.1.2
		30: Obsidian42 - BRAT v0.7.0
		31: Publish and GitHub URL v0.4.5
		32: Footnote Shortcut v0.1.2
		33: Emoji Toolbar v0.4.1
		34: Supercharged Links v0.10.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Hi @gernalix. Is this an embedded loom or are you viewing a loom file? It's possible that one of the plugins that is installed is overriding the scrolling behavior. 8.1.0 does include a scroll bar.

**Comment by trey-wallis** [comment]
https://github.com/trey-wallis/obsidian-dataloom/assets/40307803/4ebc5233-55fe-4176-bc13-62178c452bff

**Comment by trey-wallis** [comment]
@chrisweis are you getting this behavior?

**Comment by trey-wallis** [comment]
Cannot reproduce
