### ISSUE TITLE
Tag filters do not work correctly

### ISSUE THREAD

**Issue by anareaty** [trey-wallis/obsidian-dataloom#662]
### Describe the bug

I noticed that when filtering by tags I get not only rows with the chosen tag, but also rows without any tags:
![Screenshot_6](https://github.com/trey-wallis/obsidian-dataloom/assets/55949830/21202ba5-f2ac-47ee-bd69-6fe21d0cb4dc)
Also when I try to filter by empty tags I get inconsistent results. At first it doesn't work at all:
![Screenshot_5](https://github.com/trey-wallis/obsidian-dataloom/assets/55949830/316a817d-2791-46de-b83f-b4ec34aef696)
But if I change filter to something else and then back to empty tags, it suddenly works:
![Screenshot_7](https://github.com/trey-wallis/obsidian-dataloom/assets/55949830/aee518ec-e55e-4c31-834a-81431412e719)

### Steps to reproduce

Create a table with tags column, where some rows has tags and some doesn't. 

First try to filter by empty tags. Then change filter to some tag. Then change back to empty tags. See what happens.

### Expected behavior

Filters should work correctly.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.3.7
	Installer version: v1.3.4
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 145
	Restricted mode: off
	Plugins installed: 32
	Plugins enabled: 32
		1: Commander v0.5.0
		2: Custom File Explorer sorting v1.8.2
		3: Cyrillic Morpher v0.0.1
		4: Dataview v0.5.56
		5: Digital Garden v2.45.2
		6: Editing Toolbar v2.3.1
		7: Folder notes v1.4.4
		8: Home tab v1.1.2
		9: Kanban v1.5.3
		10: Links v1.2.9
		11: MetaEdit v1.8.0
		12: Obsidian42 - BRAT v0.7.0
		13: OZ Calendar v0.2.4
		14: Plugin Groups v2.1.0
		15: Pocketbook Cloud Highlight Importer v0.1.6
		16: ProZen v0.3
		17: QuickAdd v1.2.1
		18: Quiet Outline v0.3.15
		19: Sortable v0.3.1
		20: Tag Wrangler v0.5.8
		21: Typing Transformer v0.4.0
		22: Waypoint v1.4.0
		23: Workspaces Plus v0.3.3
		24: Omnivore v1.5.3
		25: Fleeting Notes Sync v0.6.1
		26: Homepage v3.3.3
		27: Query Control v0.5.0
		28: Toggle Meta Yaml v1.2.0
		29: Banners v1.3.3
		30: Better Word Count v0.9.6
		31: Templater v1.16.0
		32: DataLoom v8.1.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Hi @anareaty. Thanks for this bug report. I will look into that today

**Comment by trey-wallis** [comment]
Fixed in 8.5.0 :)
