### ISSUE TITLE
hope to add utf-8 code when export to csv file

### ISSUE THREAD

**Issue by Cyletix** [trey-wallis/obsidian-dataloom#674]
### Problem

when i export to csv file, i found my data becomes garbled

### Solution

I wish there was better support for non-English characters

**Comment by trey-wallis** [comment]
Hi. I have tried reproducing this and cannot. What kind of characters are
you using? Could you give me an example?

**Comment by trey-wallis** [comment]
Are you using a Windows system?

**Comment by Cyletix** [comment]
yes, im using windows 10, I can give you some characters as column :

------------------------------------
谱面名称,写谱时间,难度,备注
"  To The Milkyway                      ",2023-06-20,15,
BaoUner,2022-07-28,"   did not finish                   ",
GOODTEK,2022-02-09,19,7k改
LOSTAIR,2022-06-18,13,7k改
YELL!,2022-03-28,18,7k改
ピアノ三重奏,2021-06-11,did not finish,
------------------------------------

this is DataLoom Export to csv UI show, it displayed correctly, but when I Download this csv file, all characters are garbled, like this:
-----------------------------------
璋遍潰鍚嶇О | 鍐欒氨鏃堕棿 | 闅惧害 | 澶囨敞
-- | -- | -- | --
To The Milkyway | 2023-6-20 | 15 |  
BaoUner | 2022-7-28 | did not finish
GOODTEK | 2022-2-9 | 19 | 7k鏀?
LOSTAIR | 2022-6-18 | 13 | 7k鏀?
YELL! | 2022-3-28 | 18 | 7k鏀?
銉斻偄銉庝笁閲嶅 | 2021-6-11 | did not finish


by the way, the other problem i found is that I cant import any thing to DataLoom table, either Markdown Table or Excel, csv, dataview, DB Folder, json.......so if you want to reproduce this encoding problem, you must manually fill in the characters of the cells into the DataLoom table one by one, or just test one cell?

**Comment by Cyletix** [comment]
I think the problem lies in the fact that the default encoding used to create the csv file is not utf-8, can you please check the relevant code?

**Comment by trey-wallis** [comment]
@Cyletix I will check this out today after I push out the next release

**Comment by trey-wallis** [comment]
I cannot reproduce the issue on Windows 10. What kind of editor are you using to open the file? I used VSCode

**Comment by Cyletix** [comment]
I use the button in menu.
I just tried the new version 8.2.2, and now it works. That's very helpful, thanks for doing it!
