### ISSUE TITLE
Can I import existing Markdown table data into a table created in Dataloom?

### ISSUE THREAD

**Issue by Dara235711** [trey-wallis/obsidian-dataloom#675]
### Problem

Before discovering Dataloom, I had many data records in Markdown format. 
After using Dataloom, I want to import all these Markdown-formatted data into Dataloom.
But I can't find anyway to do it.
Help!

### Solution

Add a function to import external data (including table data in md format).

**Comment by trey-wallis** [comment]
@Dara235711 This has been added in 8.3.0 :)

**Comment by Dara235711** [comment]
> @Dara235711 This has been added in 8.3.0 :)
> 
> Please see: https://dataloom.xyz/other/import/

Thank you, I will try~
