### ISSUE TITLE
Documentation on formular cells in incomplete

### ISSUE THREAD

**Issue by tairun** [trey-wallis/obsidian-dataloom#680]
### Describe the bug

> https://github.com/trey-wallis/obsidian-dataloom/blob/master/docusaurus/docs/features/cells/body/body-cell-formula.mdx

The documentation on formula cells is there, but the usage information is empty. Which raises the question: Does this feature exist or not?

### Steps to reproduce

-

### Expected behavior

-

### Are you using the mobile app?

Yes

### Obsidian debug info

-

### Relevant log output

```shell
-
```

**Comment by trey-wallis** [comment]
Thanks for this. No, it is not currently implemented. I will temporarily remove the page from the documentation to avoid confusion. It is on the project roadmap. I will work it in the next week :)
