### ISSUE TITLE
Please add a search bar to the documentation site!

### ISSUE THREAD

**Issue by YousufSSyed** [trey-wallis/obsidian-dataloom#686]
### Problem

The documentation site https://dataloom.xyz/ doesn't have a search bar which makes it really inconvenient for searching for specific things to do with and about the plugin.

### Solution

I'm not a Docusaurus expert, but I recommend looking at their page about adding a search bar: https://docusaurus.io/docs/search. I spent too much looking for how to open files again with a URI and it would've been much faster with search.

**Comment by trey-wallis** [comment]
Thank you for posting this. I will add this. :)

**Comment by trey-wallis** [comment]
Added search bar.
