### ISSUE TITLE
Ability to hide the 'Calculate' area on the bottom of the table

### ISSUE THREAD

**Issue by ArcticDev78** [trey-wallis/obsidian-dataloom#688]
### Problem

I don't know if this is already possible somehow but, **would it be possible to disable or not see the 'Calculate' area on the bottom of the table**?
This is because I don't have any current use case for using the Calculate feature.

### Solution

An option to hide the 'Calculate' area on the bottom of the table

**Comment by trey-wallis** [comment]
@ArcticDev78 Yes, that is possible. I will add that in the next build.

**Comment by trey-wallis** [comment]
@ArcticDev78 Added in 8.6.0

**Comment by ArcticDev78** [comment]
Thank you so much for your work! :)
