### ISSUE TITLE
add filter by date

### ISSUE THREAD

**Issue by nosovk** [trey-wallis/obsidian-dataloom#718]
### Problem

I store expenses in loom, and it would be nice to have filters like: this month, previous month etc.
<img width="698" alt="image" src="https://github.com/trey-wallis/obsidian-dataloom/assets/1398808/e3328bc9-7ceb-4199-89a1-52f7ab5dd309">
Here is a small reproduction screen. As you can see date column is not available in filters list.

### Solution

Add support of filtering by date column filed with some predefined filters:
- this day
- this week
- this month
- Previous week
- Previous month

**Comment by trey-wallis** [comment]
@nosovk This has been added in 8.5.0 :)
