### ISSUE TITLE
Open table doesn't update when remote vault is updated

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-dataloom#730]
### Describe the bug
Using Obsidian sync, if you have 2 devices that share a remote vault and both devices have the same table open, if you update the table on the 1st device, the 2nd device's table doesn't update until you reopen the file.

### Steps to reproduce
1. Purchase an Obsidian sync license
2. Enable the sync plugin
3. Login into the Obsidian sync on 2 devices
4. Create a remote vault
5. Connect to the remove vault on both devices
6. Make sure that syncing of all files is enabled
7. Create a loom file on the 1st device
8. Open the file on the 2nd device
9. Make a change to the file on the 1st device
10. See that the 2nd device's table view doesn't update
11. Close and reopen the file on the 2nd device
12. See that the data has updated

### Expected behavior

The active view and all other views for the table file on the 2nd device should update.

### Are you using the mobile app?

No

### Obsidian debug info

N/A

**Comment by haShinui** [comment]
did you find anything to fix it?
Because I might give up on loom just because of this. Great tool but I need it an all of my devices

**Comment by trey-wallis** [comment]
Hey haShinui. Sorry for not being responsive. I am waiting to see what
happens with native Obsidian tables and databases. I don't know if this
plugin will be necessary anymore. I can take a look at this tomorrow
though. I am glad that you like DataLoom.

**Comment by haShinui** [comment]
Hello
Thanks for the fast repsonse but I bade a mistake on my side.
For some reason the Sync Plugin disbaled some Sync options, I dont know why.
But I solved it yesterday evening by reanabeling some Settings and it works Like a charm.
Sorry for takig your time and love the Plugin, really Useful.

**Comment by trey-wallis** [comment]
Fixed in 8.15.10.
