### ISSUE TITLE
Add Priority

### ISSUE THREAD

**Issue by xsinbh** [trey-wallis/obsidian-dataloom#739]
### Problem

Header type: Adding priority type.

### Solution

The cells below can be some visible elements, such as flags of different colors, or the amount of stars like the evaluation in apps. Plain text is not so striking.

**Comment by trey-wallis** [comment]
Hi @xsinbh. I think can be accomplished by using tags. You can add star icons to tag content

**Comment by xsinbh** [comment]
well, That's a good idea. Thanks for your reply!
