### ISSUE TITLE
Adding KRW(Korean Won) as the currency unit

### ISSUE THREAD

**Issue by Citatap** [trey-wallis/obsidian-dataloom#747]
### Problem

Hello,
I'm always grateful for your app with good features.

I would like to request a new feature.

* Please add ‘South Korean Won(₩, KRW)’ as the currency unit.

### Solution

Add ‘Korean Won’ as the currency unit.

![image](https://github.com/trey-wallis/obsidian-dataloom/assets/140813250/7d10f8c4-970b-4099-b054-e49ef8dec6c8)

**Comment by trey-wallis** [comment]
Hey @Citatap. Sure thing. This will be added today. :)

**Comment by trey-wallis** [comment]
Added in 8.5.0 :)
