### ISSUE TITLE
Type Unaware Sorting

### ISSUE THREAD

**Issue by CheeksTheGeek** [trey-wallis/obsidian-dataloom#749]
### Describe the bug

When I try to sort a "Number" typed column, it sorts it in the same way as texts but lexigraphic sorting is wrong for numbers.

![image](https://github.com/trey-wallis/obsidian-dataloom/assets/39400946/50247f67-21f0-47d0-9f63-f97e0c7bbda3)

### Steps to reproduce

Sort a Number type column with fields 904,  1055, 1004, 959

### Expected behavior

it should sort it like 1055, 1004, 959, 904

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.13
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103 22.5.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Obsidian Nord v0.2.0
	Snippets enabled: 5
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 20
		1: Obsidian Git v2.22.0
		2: Outliner v4.8.0
		3: Dictionary v2.22.0
		4: Copy button for code blocks v0.1.0
		5: Find orphaned files and broken links v1.9.1
		6: Editor Syntax Highlight v0.1.3
		7: Advanced Tables v0.19.1
		8: Open vault in VSCode v1.2.1
		9: Privacy Glasses v0.7.1
		10: Extended MathJax v0.4.1
		11: Paste URL into selection v1.7.0
		12: Text Generator v0.3.20
		13: Excalidraw v1.9.19
		14: Dataview v0.5.56
		15: Omnisearch v1.17.1
		16: Text Extractor v0.4.6
		17: DataLoom v8.4.1
		18: Homepage v3.5.2
		19: Auto Link Title v1.4.1
		20: Importer v1.3.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@CheeksTheGeek Thanks for posting this. I will push an update for this tomorrow.

**Comment by CheeksTheGeek** [comment]
Wow! Thanks for such a quick reply and confirmation!!

**Comment by trey-wallis** [comment]
@CheeksTheGeek Could you try updating to 8.5.0? I am not getting that behavior.

**Comment by trey-wallis** [comment]
Closed as this should be fix.
