### ISSUE TITLE
Exported loom data order inconsistent with columns

### ISSUE THREAD

**Issue by Trizotto** [trey-wallis/obsidian-dataloom#750]
### Describe the bug

Exporting a data loom to csv or markdown gives me a file (or plain text) with inconsistent data. The row data makes sense, each row has all of the data it should, but the ordering does not match the column names at the top, or the order of previous/next line.

Example dataloom:
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/65738584/df860695-6e07-46a7-9eda-1bcad17c990b)

Exported data: 
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/65738584/99aca08d-568f-48fb-aa03-c2549754c94b)

### Steps to reproduce

On a new loom, create all columns needed and input a row of data

Try creating a new row of data, but change column order before adding data. Check exported data
Try changing the column order (different than initial order) before creating a new row, then adding data. Check exported data

The order of the exported data seem to follow the order of the columns in the moment the row was created (for each row, separately)

### Expected behavior

All rows to follow the same column order

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.13
	Installer version: v1.4.13
	Operating system: Windows 10 Education 10.0.22621
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.1.1
	Snippets enabled: 11
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 21
		1: Periodic Notes v0.0.17
		2: Calendar v1.5.10
		3: Hider v1.3.1
		4: Buttons v0.4.19
		5: Contextual Typography v2.2.5
		6: Excalidraw v1.9.19
		7: Task Collector (TC) v1.0.12
		8: MySnippets v1.2.3
		9: Templater v1.16.0
		10: Minimal Theme Settings v7.2.2
		11: Style Settings v1.0.7
		12: Hide Sidebars on Window Resize v1.1.0
		13: Advanced Tables v0.19.1
		14: Sortable v0.3.1
		15: Readwise Official v2.0.1
		16: Natural Language Dates v0.6.1
		17: Global Search and Replace v0.3.0
		18: Dataview v0.5.58
		19: Remember cursor position v1.0.8
		20: Supercharged Links v0.10.3
		21: DataLoom v8.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@Trizotto Thanks for finding this. Will look into tomorrow.

**Comment by trey-wallis** [comment]
Is this happening 8.5.0?

**Comment by trey-wallis** [comment]
There used to be a delay between updating the table and exporting that. So if you were to reorder the columns, the export model might take a few seconds to update. That is no longer the case.

**Comment by Trizotto** [comment]
Yes it still happens with 8.5.0. 

I just reproduced it after updating to 8.5.0 by creating a new dataloom, then following the steps I described. 

Changing the column order before creating a new row and adding its data seems to trigger this bug for me.

**Comment by trey-wallis** [comment]
@Trizotto Sorry, I seem to have skipped over your steps to reproduce. I was able to reproduce it.

**Comment by trey-wallis** [comment]
Fixed in 8.6.0.
