### ISSUE TITLE
input duplication using Japanese input method

### ISSUE THREAD

**Issue by Zhumatic** [trey-wallis/obsidian-dataloom#760]
### Describe the bug

using Japanese input method causing input duplication

### Steps to reproduce

using Japanese input method, write in the cell for example: テスト, hit enter it displays テストテスト

### Expected behavior

shows テスト as exactly inputted

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.13
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 22.6.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Tokyo Night v0.1.11
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 6
		1: Advanced Tables v0.19.1
		2: Heading Level Indent v1.0.3
		3: Quick Latex for Obsidian v2.6.3
		4: Outliner v4.8.0
		5: Icon Folder v2.2.1
		6: DataLoom v8.4.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@Zhumatic Could you send me a video of this? Are you using a standard Japanese keyboard in MacOS as well?

**Comment by trey-wallis** [comment]
Is this still a problem in DataLoom 8.12.0?

**Comment by Zhumatic** [comment]
just tried, now it is functioning normally with Japanese input. Thanks a lot! 🌻

**Comment by trey-wallis** [comment]
Glad to hear! Thanks for the update.
