### ISSUE TITLE
Add a more advanced multi-select

### ISSUE THREAD

**Issue by trey-wallis** [trey-wallis/obsidian-dataloom#775]
### Problem

The default `select` in the filter is not very accessible.

### Solution

<img width="278" alt="image" src="https://github.com/trey-wallis/obsidian-dataloom/assets/40307803/313085ab-ff90-4c83-a564-925174e8176e">

**Comment by Connor-yang96** [comment]
really need this feature.

**Comment by trey-wallis** [comment]
@Connor-yang96 Added in 8.10.0 :)
