### ISSUE TITLE
After the last update dragging doesn't work anymore

### ISSUE THREAD

**Issue by Flexit07** [trey-wallis/obsidian-dataloom#788]
### Describe the bug

as in title.
After last update at 8.6.3 dragging rows is becomed impossible

### Steps to reproduce

I've just updated the plugin

### Expected behavior

.

### Are you using the mobile app?

No

### Obsidian debug info

.

### Relevant log output

```shell
.
```

**Comment by trey-wallis** [comment]
Thanks for posting this. Will update today.
