### ISSUE TITLE
There was a bug where importing CSV data with non-English 2-byte characters would not import.

### ISSUE THREAD

**Issue by OPEN1004MIND** [trey-wallis/obsidian-dataloom#792]
### Describe the bug

The data doesn't seem to be loading, or it's loading in the wrong column, and it doesn't seem to be loading with special characters.

### Steps to reproduce

I created a Loom board and hit import materials to paste the csv materials into a string. 
Currently, it doesn't seem to be possible to import csv files into par, 
so I pasted the string in the way shown in the example video.

### Expected behavior

I would like to be able to import characters from non-English UNI codes.

### Are you using the mobile app?

No

### Obsidian debug info

None

**Comment by trey-wallis** [comment]
I just got Arabic to work. Could you send me the CSV file that you are using for this?

**Comment by trey-wallis** [comment]
I have reproduced this bug. If you have a CSV file with unicode characters, please make sure that the CSV file is in `UTF-8` format.

**Comment by OPEN1004MIND** [comment]
Thank you answer. I will try again
