### ISSUE TITLE
Autofill of obsidian link isn't working

### ISSUE THREAD

**Issue by 42ama** [trey-wallis/obsidian-dataloom#793]
### Describe the bug

When autofilling an obsidian link, the autofill is not working
![dataloom-insert-link-bug](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/4a222116-bca5-4118-a5a9-3e62c1fe24bf)

### Steps to reproduce

1. Open loom.
2. Start typing "[[" and existing page name.
3. Click on any page from dropdown list or press Enter.

### Expected behavior

Page name autofills in current double square brackets block.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 22
	Plugins enabled: 18
		1: Templater v1.16.0
		2: TagFolder v0.18.0
		3: Excalidraw v1.9.19
		4: Dataview v0.5.59
		5: Advanced Tables v0.19.1
		6: Periodic Notes v0.0.17
		7: Rollover Daily Todos v1.1.7
		8: Admonition v10.1.1
		9: Obsidian Git v2.22.0
		10: Emoji Toolbar v0.4.1
		11: DataLoom v8.6.4
		12: Calendar v1.5.10
		13: Underline v1.2.1
		14: Surfing v0.8.16
		15: Editor Syntax Highlight v0.1.3
		16: Numerals v1.2.0
		17: Homepage v3.5.2
		18: Buttons v0.4.19

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
Empty
```

**Comment by trey-wallis** [comment]
Hey @42ama. Thanks for posting this issue. I am currently working on a big feature, I then will fix some of these bugs.

**Comment by trey-wallis** [comment]
Related #737

**Comment by trey-wallis** [comment]
Fixed in 8.8.0.
