### ISSUE TITLE
Sorting by File is inconsistent

### ISSUE THREAD

**Issue by seanchiggins** [trey-wallis/obsidian-dataloom#796]
### Describe the bug

When I sort my Loom by File, the sorting is inconsistent consistently, meaning the order is incorrect, but it does it all the time.

![Screenshot 2023-10-03 at 2 57 07 PM](https://github.com/trey-wallis/obsidian-dataloom/assets/66333913/d7912c1d-2db3-4e9d-8c0e-7b8e75ac3a4f)

### Steps to reproduce

Disable sorting, re-enable sorting.

### Expected behavior

I expect the files to be sorted in alphabetical order.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:43 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T6000 23.0.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: Minimal v7.2.1
	Snippets enabled: 2
	Restricted mode: off
	Plugins installed: 21
	Plugins enabled: 21
		1: Admonition v10.1.1
		2: Dataview v0.5.59
		3: Note Refactor v1.8.2
		4: css snippets v0.1.2
		5: Pandoc Plugin v0.4.1
		6: Outliner v4.8.0
		7: Excel to Markdown Table v0.4.0
		8: Imgur Plugin v2.2.1
		9: Text Generator v0.3.20
		10: ExcaliBrain v0.2.9
		11: Plugin Update Tracker v1.5.2
		12: Homepage v3.5.2
		13: Mindmap NextGen v1.9.0
		14: Commander v0.5.0
		15: Longform v2.0.3
		16: DB Folder v3.5.0
		17: DataLoom v8.6.4
		18: Excalidraw v1.9.20
		19: Minimal Theme Settings v7.2.4
		20: Templater v1.16.3
		21: Text Extractor v0.4.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@seanchiggins Fixed in 8.13.0
