### ISSUE TITLE
Could not create Loom File depending on settings

### ISSUE THREAD

**Issue by aubreyz** [trey-wallis/obsidian-dataloom#797]
### Describe the bug

I am just starting up. I have my obsidian attachments set to go to a folder attachments subordinate to the md file in question. 

If Look is set with Create New Loom in attachment folder OFF, all is fine (albeit the loom is created at the vault root which is bad). 

If toggled ON I get error "Loom file could not be created"

If I set a specific Looms Folder it is OK. 

### Steps to reproduce

As above

### Expected behavior

Does not work as expected with Attachments folders unless a specific attachment folder is set. This needs to be much clearer. 

### Are you using the mobile app?

No

### Obsidian debug info

Not relevant

### Relevant log output

```shell
Loom file could not be created
```

**Comment by trey-wallis** [comment]
Fixed in 8.9.0.
