### ISSUE TITLE
file was broken

### ISSUE THREAD

**Issue by yakee99** [trey-wallis/obsidian-dataloom#798]
### Describe the bug

file was broken

### Steps to reproduce

no

### Expected behavior

no

### Are you using the mobile app?

Yes

### Obsidian debug info

Plugin version: 8.6.4
File version: 8.6.4
Failed migration: null
Error message: {
  "model": {
    "columns": [
      null,
      {
        "type": "Expected \"text\" | \"embed\" | \"file\" | \"number\" | \"tag\" | \"multi-tag\" | \"date\" | \"checkbox\" | \"creation-time\" | \"last-edited-time\", but was missing"
      }
    ]
  }
}

### Relevant log output

```shell
Plugin version: 8.6.4
File version: 8.6.4
Failed migration: null
Error message: {
  "model": {
    "columns": [
      null,
      {
        "type": "Expected \"text\" | \"embed\" | \"file\" | \"number\" | \"tag\" | \"multi-tag\" | \"date\" | \"checkbox\" | \"creation-time\" | \"last-edited-time\", but was missing"
      }
    ]
  }
}
```

**Comment by trey-wallis** [comment]
If you need help, please post your loom file content, and I can fix it for you.

**Comment by yakee99** [comment]
yes,its solved. when i change one column from checkbox to text, the content type was missed. and finally i find that. thank your help.
