### ISSUE TITLE
It creates the Loom file in the attachments folder in the root directory instead of the subfolder

### ISSUE THREAD

**Issue by mikdatdogru** [trey-wallis/obsidian-dataloom#806]
### Describe the bug

When I create an embedded loom in the folder where the note file is located, it creates the loom file in the root directory.

https://github.com/trey-wallis/obsidian-dataloom/assets/10121255/1d416d64-1fd1-445d-9511-2b5350a090b6

### Steps to reproduce

* DataLoom Options > Enable Create looms in the attachments folder feature
* From the Files & Links Menu, select Default attachment location setting as subfolder and change the foldername.
* create a loom file with the quick command "Create loom and embed it into current file" option in the note under any subfolder

### Expected behavior

The created loom file must be in the Attachments folder under the folder where the relevant loom file is located.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.14
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.0.0: Fri Sep 15 14:41:34 PDT 2023; root:xnu-10002.1.13~1/RELEASE_ARM64_T8103 23.0.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: DataLoom v8.7.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
app.js:1 Uncaught (in promise) Error: Folder already exists.
    at t.<anonymous> (app.js:1:706031)
    at app.js:1:237027
    at Object.next (app.js:1:237132)
    at a (app.js:1:235850)
(anonymous) @ app.js:1
(anonymous) @ app.js:1
(anonymous) @ app.js:1
a @ app.js:1
Promise.then (async)
step @ plugin:notion-like-tables:73
eval @ plugin:notion-like-tables:74
__async @ plugin:notion-like-tables:58
editorCallback @ plugin:notion-like-tables:63704
e.mobileOnly.It.isMobile.e.checkCallback @ app.js:1
n_ @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
(anonymous) @ app.js:1
e.handleKey @ app.js:1
e.onKeyEvent @ app.js:1



=====
DataLoom Debug Mod Enabled
====
plugin:notion-like-tables:63489 main handleClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:63495 main handleKeyDown
plugin:notion-like-tables:63495 main handleKeyDown
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:42354 useMenuEvents onCloseAll
plugin:notion-like-tables:63495 main handleKeyDown
plugin:notion-like-tables:63495 main handleKeyDown
plugin:notion-like-tables:63495 main handleKeyDown
plugin:notion-like-tables:63495 main handleKeyDown
plugin:notion-like-tables:63489 main handleClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
plugin:notion-like-tables:42354 useMenuEvents handleGlobalClick
```

**Comment by trey-wallis** [comment]
Fixed in 8.9.0
