### ISSUE TITLE
Does not handle list type in frontmatter. It also endup deleting the existing value

### ISSUE THREAD

**Issue by pravin-d** [trey-wallis/obsidian-dataloom#810]
### Describe the bug

When trying to display the frontmatter using the plugin, it deletes the content of the key if it is of type list

### Steps to reproduce

My FrontMatter

Note.md
---
something:
 - one
 - two
---

1. Create a database
2. Source being folder containing the above file
3. Add a new column, select type as FrontMatter
4. Select custom and enter the key name -> something
5. The column value is empty
6. Check the actual file. The value for something in the file also becomes empty

### Expected behavior

Frontmatter -> keys of type list should either be shown as list in database table or should say the type is not supported. Should not delete the existing values.
Also the column type does not have type list.

### Are you using the mobile app?

No

### Obsidian debug info

NA

**Comment by trey-wallis** [comment]
I'm sorry if this caused any data loss. Will look into this today.

**Comment by trey-wallis** [comment]
@pravin-d Fixed in 8.12.0
