### ISSUE TITLE
CSV import just...doesn't go anywhere

### ISSUE THREAD

**Issue by leehauser** [trey-wallis/obsidian-dataloom#813]
### Describe the bug

A CSV exported from Excel never allows me to "Finish" an import. I have tried multiple variants of the export (plain CSV, Excel UTF-8 CSV), multiple import methods (with an without marked headers, with and without pre-made columns), "Finish" just doesn't do anything.

### Steps to reproduce

The original file was in Apple Numbers. I exported to CSV (which was very ugly), opened the CSV in Excel (for Windows) and re-exported the file as both a UTF-8 CSV and a plain CSV. I attempted to import both into Dataloom, both into an empty loom and into a loom with the columns pre-defined, with and without first-row-as-titles checked. After a little difficulty I figured out how to match the columns. Dataloom seems to recognize the data; it shows a preview as I match columns. But when all the checkmarks are green, I click the Finish button and nothing at all happens. 

I am attempting this on my work Windows machine, which is in some respects rather tightly locked down but runs Obsidian just fine in all other respects. I'll be trying it on my Mac at home this evening. Attached are my CSV files.

The Numbers Excel export:
[BooksRead-Numbers.xlsx](https://github.com/trey-wallis/obsidian-dataloom/files/13078956/BooksRead-Numbers.xlsx) 

The Numbers CSV export:
[BooksRead-Numbers.csv](https://github.com/trey-wallis/obsidian-dataloom/files/13078959/BooksRead-Numbers.csv)

The Excel UF8 CSV export:
[BooksRead-UTF8.csv](https://github.com/trey-wallis/obsidian-dataloom/files/13079004/BooksRead-UTF8.csv)

The Excel plain CSV export:
[BooksRead-plainCSV.csv](https://github.com/trey-wallis/obsidian-dataloom/files/13079006/BooksRead-plainCSV.csv)

### Expected behavior

Once all the columns are matched up, I expect "Finish" to populate the loom with the data from my csv files

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Enterprise 10.0.19045
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 13
	Plugins enabled: 9
		1: Pandoc Plugin v0.4.1
		2: Calendar v1.5.10
		3: Advanced Tables v0.19.1
		4: Archiver v0.26.1
		5: Plaintext v0.3.0
		6: MSG Handler v0.0.6
		7: Tasks v4.9.0
		8: Importer v1.5.2
		9: DataLoom v8.7.2

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
I don't see any relevant logs
```

**Comment by leehauser** [comment]
As a followup, I have tried this on Obsidian on my Mac, with the same result.

**Comment by henan715** [comment]
i meet the same question, i solved this by re-check my dataLoom column type, found that one column type is embed, and change it to text, maybe you could try?

**Comment by leehauser** [comment]
OK, thanks to henan715's comment, I'm closing this one. When I first tried to import I had two date columns set as "date." Once I created a new loom and called _all_ the columns "text", it imported without any difficulties.

**Comment by trey-wallis** [comment]
Hi @leehauser. There is still a bug it seems. I'm going to reopen it and fix this.

**Comment by leehauser** [comment]
If it makes any different, both fields came out of Numbers as mm/dd/yy. And even though the files had a row containing the titles, and I asked the import to see the first row as titles, it did not...I ended up with a blank row before my data, and a blank column to the left. There were only nine columns in total, so titling them took all of two minutes. I did experimentally try to convert the two date columns to date format, but they just looked empty until I turned them back to text (no data loss). I was more than happy to get what I did.

**Comment by trey-wallis** [comment]
Thank you for providing all those CSV files. There seem to be 2-3 bugs at play. Will push out a fix shortly, I believe.

**Comment by trey-wallis** [comment]
@leehauser Fixed in 8.12.0. Please open up a new issue if this persists. Thanks :)

**Comment by leehauser** [comment]
Thanks, Trey. Glad I could help. On Nov 14, 2023, at 10:11 PM, Trey Wallis ***@***.***> wrote:﻿
@leehauser Fixed in 8.12.0. Please open up a new issue if this persists. Thanks :)
