### ISSUE TITLE
Shortcut for inserting date and time into a cell

### ISSUE THREAD

**Issue by bbqian11** [trey-wallis/obsidian-dataloom#814]
### Problem

In most excel-like programs, we have shortcuts to add the current date and time.
Currently the templates do not work in datalooms - which makes it hard to insert the date, time and datetime combo.

### Solution

any one of the below solutions should suffice

- column type of 'date' could have a feature to insert current date and/or time
- column type of 'date' could have a feature to auto populate current date and/or time when row is created
- Command to quickly insert date, time or datetime combo.
- Parse obsidian templates in the cell
- shortcut key insert date and time.

**Comment by Waylandite** [comment]
I need this too.  to type  the date is an unhappy experience

**Comment by trey-wallis** [comment]
@bbqian11 @Waylandite I added a button called "Today" in 8.14.0. Please check it out :)

**Comment by bbqian11** [comment]
Exactly what I wanted. Thanks a lot
Closing this item.
