### ISSUE TITLE
Automatic sorting will not be applied after changing data in the table.

### ISSUE THREAD

**Issue by 42ama** [trey-wallis/obsidian-dataloom#815]
### Describe the bug

Automatic sorting will not be applied after changing data in the table.
![dataloom-sort-bug](https://github.com/trey-wallis/obsidian-dataloom/assets/45532431/97c6f268-4e06-41d2-8560-00d570b06336)

### Steps to reproduce

1. Open loom.
2. Sort loom by any column.
3. Change data in sorted column, which should result in the sorting being updated.

### Expected behavior

The sorting should be automatically updated.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 23
	Plugins enabled: 19
		1: Templater v1.16.4
		2: TagFolder v0.18.3
		3: Dataview v0.5.61
		4: Advanced Tables v0.19.1
		5: Periodic Notes v0.0.17
		6: Rollover Daily Todos v1.1.7
		7: Admonition v10.1.1
		8: Obsidian Git v2.22.0
		9: Emoji Toolbar v0.4.1
		10: DataLoom v8.7.2
		11: Calendar v1.5.10
		12: Underline v1.2.1
		13: Surfing v0.8.16
		14: Editor Syntax Highlight v0.1.3
		15: Numerals v1.2.0
		16: Buttons v0.4.19
		17: Find orphaned files and broken links v1.9.1
		18: Excalidraw v1.9.26
		19: Homepage v3.6.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Hey @42ama. I will add this to my next in queue.

**Comment by trey-wallis** [comment]
Fixed in 8.11.2
