### ISSUE TITLE
Support subfolders in sources

### ISSUE THREAD

**Issue by anareaty** [trey-wallis/obsidian-dataloom#830]
### Problem

When I select the folder as the source, I only see the files directly in this folder, but not in the subfolders.

### Solution

It should be possible to see all the files in the folder, including the ones in subfolders.

**Comment by trey-wallis** [comment]
Thanks for posting this. This will be the next feature that is added :)

**Comment by trey-wallis** [comment]
Added in 8.11.0. All folder sources will now show subfolders by default.
