### ISSUE TITLE
Handling of checkboxes is different from Obsidians properties

### ISSUE THREAD

**Issue by thomas-esau** [trey-wallis/obsidian-dataloom#851]
### Describe the bug

When I choose a folder as source that contains checkboxes as key/value pair in the yaml frontmatter, Dataloom puts in the following values: (checkbox: "true") for checked and (checkbox: "[ ]") for unchecked. Obsidian properties handles checkboxes this way: (checkbox: true) for checked and (checkbox: true) for unchecked; the checkbox values are not surrounded by quotation marks. Unfortunately, Dataloom overwrites the Obsidian format.

You can see this behaviour in my recording (sorry for the quality):
![13-36-47 - Trim](https://github.com/trey-wallis/obsidian-dataloom/assets/46598525/3bfe5e6a-e865-4a0f-b34b-89d6fc25b5e2)

### Steps to reproduce

1. Create a folder with a note. 
2. Add a checkbox property to the note.
3. Add this folder in a Loom as source.
4. Add a new column with checkbox as type and use the checkbox frontmatter key.

### Expected behavior

"checkbox" should have the following values: 
checkbox: true
or
checkbox: false

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Education 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: on
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: DataLoom v8.11.3

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
@thomas-esau Fixed in 8.13.0
