### ISSUE TITLE
Unable to import from csv

### ISSUE THREAD

**Issue by ratanbalaji** [trey-wallis/obsidian-dataloom#877]
### Describe the bug

Import data from csv files after completing the "Import" wizard/ pop-up doesn't actually load the data from the file. The table on the screen remains as in. Tried the same in the Sandbox vault as well and yet I had no success in importing the csv file data onto the loom file screen.

### Steps to reproduce

Create a new loom file. Perform the import process with a csv file. Choose file based or clipboard based approach. Complete assigning the columns from the file onto the loom file.

### Expected behavior

The data from the csv file is expected to be loaded onto the loom file as table.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.2.0: Fri Oct 13 09:27:54 PDT 2023; root:xnu-10002.60.54~14/RELEASE_ARM64_T6000 23.2.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Prism v3.4.2
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 20
	Plugins enabled: 18
		1: Calendar v1.5.10
		2: Natural Language Dates v0.6.1
		3: Dataview v0.5.64
		4: Advanced Tables v0.19.1
		5: Templater v1.18.1
		6: Recent Files v1.3.8
		7: Multi-Column Markdown v0.8.3
		8: Style Settings v1.0.7
		9: Excalidraw v2.0.3
		10: QuickAdd v1.6.0
		11: Advanced URI v1.38.1
		12: Tasks v5.1.1
		13: Admonition v10.1.1
		14: Hotkeys for templates v1.4.3
		15: List Callouts v1.2.0
		16: Callout Manager v1.0.1
		17: Projects v1.17.1
		18: DataLoom v8.14.0

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Hi @ratanbalaji. Thanks for your bug report. Could you provide the file that you're trying and a screenshot of any errors?

**Comment by trey-wallis** [comment]
Nevermind. I was able to reproduce it. Will look into this.

**Comment by trey-wallis** [comment]
It looks like it is importing. It's just not updating.

**Comment by trey-wallis** [comment]
I will push out a fix shortly

**Comment by trey-wallis** [comment]
Please try it now in 8.14.1

**Comment by ratanbalaji** [comment]
Thanks for fixing it so quickly! Appreciate it.
