### ISSUE TITLE
File broken - need help too debug

### ISSUE THREAD

**Issue by somster-boop** [trey-wallis/obsidian-dataloom#899]
### Describe the bug

Plugin version: 8.15.6
File version: 8.15.4
Failed migration: null
Error message: {
  "model": {
    "filters": [
      null,
      null,
      null,
      null,
      {
        "text": "Expected string, but was missing"
      }
    ]
  }
}

### Steps to reproduce

The bug appeared on opening the file. I checked for the update and updated the plugin. The bug stays the same. 

### Expected behavior

Expected the file to open

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.14
	Operating system: Darwin Kernel Version 22.6.0: Wed Oct  4 21:25:26 PDT 2023; root:xnu-8796.141.3.701.17~4/RELEASE_X86_64 22.6.0
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 7
	Restricted mode: off
	Plugins installed: 105
	Plugins enabled: 49
		1: Style Settings v1.0.7
		2: Pane Relief v0.5.2
		3: Recent Files v1.3.8
		4: Copy button for code blocks v0.2.0
		5: Customizable Page Header and Title Bar v4.6.2
		6: Hider v1.3.1
		7: Show Current File Path v0.5.2
		8: Grandfather v1.0.1
		9: Snippet Downloader v2.0.1
		10: Hotkey Helper v0.3.18
		11: Commander v0.5.1
		12: Copy Block Link v1.0.4
		13: Customizable Menu v2.2.0
		14: Carry-Forward v1.4.5
		15: Drag-n-Drop for blocks v1.2.0
		16: Smart Random Note v0.2.2
		17: Templater v1.18.3
		18: Better File Link v1.1.4
		19: Quick Switcher++ v3.3.9
		20: Auto Card Link v1.2.2
		21: Dataview v0.5.64
		22: Find orphaned files and broken links v1.9.1
		23: Highlightr v1.2.2
		24: Hotkeys++ v0.2.7
		25: Hotkeys for specific files v1.4.0
		26: Pluck v1.0.1
		27: Quick Explorer v0.2.8
		28: Supercharged Links v0.11.1
		29: Obsidian42 - Strange New Worlds (SNW) v1.2.3
		30: Scroll to Top Plugin v2.1.3
		31: Super Simple Time Tracker v0.1.8
		32: Note Content Pusher v1.0.4
		33: Matter v1.1.4
		34: Table Generator v1.4.1
		35: Tag Summary v2.1.5
		36: Chronology v1.1.11
		37: Omnisearch v1.19.0
		38: Mousewheel Image zoom v1.0.19
		39: Markdown Table Editor v0.3.1
		40: Optimize Canvas Connections v1.0.0
		41: Canvas Filter v0.9.2
		42: Canvas CSS class v2.2.2
		43: Canvas Mindmap v0.1.3
		44: Snippetor v0.4.4
		45: MySnippets v1.2.3
		46: Link Exploder v0.3.0
		47: Frontmatter Links v1.2.7
		48: Buttons v0.4.19
		49: DataLoom v8.15.6

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Hmm that's odd. The immediate fix for your file is to look at the 5th
filter and add a "text": "" property

**Comment by trey-wallis** [comment]
@somster-boop This should be fixed in 8.15.7. Please update the plugin and try opening your loom file again :)

**Comment by somster-boop** [comment]
Thank you for your prompt help. The immediate fix solution worked and will also update the plugin.
