### ISSUE TITLE
Line breaks avoid a proper export to markdown or CSV

### ISSUE THREAD

**Issue by Calisten** [trey-wallis/obsidian-dataloom#901]
### Describe the bug

Line breaks (whether those made with Shift + Enter or by inserting a br tag) avoid to made a proper export to mardown or CSV :

![Loom-Example](https://github.com/trey-wallis/obsidian-dataloom/assets/153132812/f79b8530-576f-476d-80c2-eaff8f8d5717)
Capture of the exported the table
![Loom-Example-Export](https://github.com/trey-wallis/obsidian-dataloom/assets/153132812/799641a3-176d-4eab-b399-2ac418377c75)

### Steps to reproduce

1. Add a line break (with shift+enter ou by inserting a br tag in any cell) in any loom table
2. Click on export and select a markdown as a file option (for example)
3. Copy to clipboard the code and paste it in a note

### Expected behavior

- Detect and remove linebreak when exporting so that the export can be be made properly 
- Or ideally, integrate the line breaks in the exported table.

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Windows 10 Pro 10.0.22621
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 7
	Restricted mode: off
	Plugins installed: 44
	Plugins enabled: 34
		1: Dataview v0.5.64
		2: Excalidraw v2.0.7
		3: AutoMOC v1.3.4
		4: Buttons v0.4.19
		5: Dangling links v0.3.0
		6: Dynamic Table of Contents v0.0.27
		7: Highlightr v1.2.2
		8: Hotkeys for Bookmarks v1.1.0
		9: Kanban v1.5.3
		10: Markdown Table Editor v0.3.1
		11: Obsidian Charts v3.8.2
		12: Number Headings v1.16.0
		13: Pandoc Plugin v0.4.1
		14: PDF Highlights v0.0.4
		15: QuickAdd v1.6.1
		16: Tag Page Preview v0.0.12
		17: Text Format v2.2.9
		18: Editing Toolbar v2.4.0
		19: Diagrams v1.5.0
		20: Quiet Outline v0.3.17
		21: DB Folder v3.5.0
		22: Scales and Chords v1.0.1
		23: Home tab v1.1.2
		24: Homepage v3.6.0
		25: DataLoom v8.15.7
		26: Obsidian42 - Strange New Worlds (SNW) v1.2.3
		27: Footnote Shortcut v0.1.3
		28: Tidy Footnotes v0.1.1
		29: Checklist v2.2.13
		30: Tag Wrangler v0.6.1
		31: Recent Files v1.3.8
		32: Webpage HTML Export v1.7.3
		33: Copy as HTML v1.1.3
		34: Copy Block Link v1.0.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by Calisten** [comment]
Hi, for those who have the same need to me to export in markdown table, here is a workaround : instead of using shift + enter to add a line break in a cell, just add <br> tag.

**Comment by trey-wallis** [comment]
@Calisten Thanks for posting on this. I will work on fixing this.
