### ISSUE TITLE
Something wrong when import from csv 

### ISSUE THREAD

**Issue by jinsihou19** [trey-wallis/obsidian-dataloom#907]
### Describe the bug

When a file in CSV format is split using tabs, if there are null values, the data cannot be imported.
Error in console：
```JS
Uncaught TypeError: Cannot read properties of undefined (reading 'trim')
    at eval (plugin:notion-like-tables:63211:48)
    at Array.forEach (<anonymous>)
    at eval (plugin:notion-like-tables:63202:17)
    at Array.map (<anonymous>)
    at addImportData (plugin:notion-like-tables:63198:55)
    at handleFinishClick (plugin:notion-like-tables:63724:22)
    at handleNextClick (plugin:notion-like-tables:62075:7)
    at handleClick (plugin:notion-like-tables:54356:32)
```

### Steps to reproduce

import test.csv，the data cannot be imported. 
[test.csv](https://github.com/trey-wallis/obsidian-dataloom/files/13692576/test.csv)

### Expected behavior

The data from the csv file is expected to be loaded as table.

### Are you using the mobile app?

Yes

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:10 PST 2023; root:xnu-10002.61.3~2/RELEASE_X86_64 23.2.0
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 2
	Plugins enabled: 1
		1: DataLoom v8.15.8

**Comment by trey-wallis** [comment]
Fixed in 8.5.9
