### ISSUE TITLE
Table scrolls to bottom when deleting a row

### ISSUE THREAD

**Issue by githubwhatsittoyou** [trey-wallis/obsidian-dataloom#915]
### Describe the bug

When deleting a row, the view scrolls all the way to the bottom after deleting two rows consecutively, making the user go all the way to the top again

### Steps to reproduce

Delete two different rows

### Expected behavior

The view stays wherever it is and does not scroll anywhere

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:59:33 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T8112 23.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: adapt to system
	Community theme: Everforest v0.0.0
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 5
	Plugins enabled: 3
		1: DataLoom v8.15.10
		2: Natural Language Dates v0.6.2
		3: Privacy Glasses v0.7.4

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Fixed in 8.15.11
