### ISSUE TITLE
Table Cell content gets deleted after creating a new row

### ISSUE THREAD

**Issue by kbonnici** [trey-wallis/obsidian-dataloom#916]
### Describe the bug

Pressing `+ New` button creates a new row as expected, but around half a second later any content that has been typed into that row is deleted.

### Steps to reproduce

* Click `+ New` button to add new row to data loom table
* Type into any of the cells in the new row
* Half a second later, whatever content was typed is automatically removed

### Expected behavior

Immediately entering a cell and typing should preserve whatever I type

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.5.3
	Installer version: v1.5.3
	Operating system: Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 23.2.0
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: Minimal v7.4.5
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 9
	Plugins enabled: 9
		1: Minimal Theme Settings v7.3.1
		2: Calendar v1.5.10
		3: Excalidraw v2.0.13
		4: Dataview v0.5.64
		5: Advanced Tables v0.20.0
		6: Highlightr v1.2.2
		7: DataLoom v8.15.10
		8: Paste URL into selection v1.7.0
		9: Iconize v2.8.1

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

### Relevant log output

```shell
handleNewRowClick
plugin:notion-like-tables:46914 App handleClick
plugin:notion-like-tables:46914 MenuProvider clearMenuTriggerFocus
plugin:notion-like-tables:46914 LoomStateProvider saving state to disk!
plugin:notion-like-tables:46914 updateRowsFromSources called
```

**Comment by kbonnici** [comment]
I suspect the culprit is `updateRowsFromSources` or some other higher level function call.

I asked about this behaviour on [reddit](https://www.reddit.com/r/ObsidianMD/comments/18u6r3e/comment/kfimhhz/?context=3) and someone commented saying that Obsidian released an update recently which made some changes to the way tables are handled. Perhaps that is a good place to start.

**Comment by jboulter11** [comment]
I'm having a similar issue.  `updateRowsFromSources` is getting called and disrupting table editing of any kind, reverting changes as they're being made.

**Comment by jboulter11** [comment]
Ah, when the table fully locks up I do seem to see two `updateRowsFromSources` calls showing up when it happens.  Here's what I see logged when the lockup happens:
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/6633472/32ac4e7f-242e-48c2-8b80-a93d3f2f523b)

**Comment by kbonnici** [comment]
The problem still occurs even with all other plugins disabled. I dont experience this locking behaviour you describe though.

When i get a chance i will test with a fresh install of obsidian and report back.

**Comment by trey-wallis** [comment]
Sorry I have been busy for the holidays. Will look into this
