### ISSUE TITLE
Videos of docs not working on Firefox

### ISSUE THREAD

**Issue by robsonsobral** [trey-wallis/obsidian-dataloom#921]
### Describe the bug

The videos on documentation don't run on Firefox.

### Steps to reproduce

Try to navigate the docs using Firefox.

### Expected behavior

To play the videos.

### Are you using the mobile app?

No

### Obsidian debug info

Not relevant.

**Comment by trey-wallis** [comment]
The videos work for me in Firefox. Which version are you using?

**Comment by robsonsobral** [comment]
That's weird. I tested on two different Windows computers.

**Comment by robsonsobral** [comment]
Well... I tried to get you some screenshots, but... They're working now. I'm so sorry!
