### ISSUE TITLE
DataLoom cannot render file

### ISSUE THREAD

**Issue by RoboG-11** [trey-wallis/obsidian-dataloom#939]
### Describe the bug

Hi, I have been using the extension for some university work. But today it closed by itself and I get the message of:
Opps
DataLoom cannot render file
Error message
Unexpected end of JSON input

I opened the corresponding .loom file to do the suggested steps, but the file IS EMPTY!!!!
I already checked the recycle garbage can and there is nothing, how can I retrieve the information I had in the file?

![image](https://github.com/trey-wallis/obsidian-dataloom/assets/106283018/717ff3b0-d4d4-495c-8617-1f55e0c42c77)
![image](https://github.com/trey-wallis/obsidian-dataloom/assets/106283018/ac054b5b-7162-418f-af2a-405cc6c29dc1)

I NEED TO RETRIEVE THE INFORMATION URGENTLY!!!!!!

### Steps to reproduce

just closed on its own

### Expected behavior

I need to recover my data!!!

### Are you using the mobile app?

No

### Obsidian debug info

SYSTEM INFO:
	Obsidian version: v1.5.11
	Installer version: v1.4.16
	Operating system: Windows 10 Home Single Language 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 6
	Plugins enabled: 6
		1: Calendar v1.5.10
		2: Style Settings v1.0.7
		3: Excalidraw v2.0.23
		4: Dataview v0.5.64
		5: MAKE.md v0.9.5
		6: DataLoom v8.15.12

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.

**Comment by trey-wallis** [comment]
Hi. That is bizarre. This is the first issue of that ever happening. You
don't have any backups of your files?

Do you still have the tab open with a table loaded? If not, there's nothing
that can be done.

**Comment by RoboG-11** [comment]
OMG, so I lost all the information that was in the file????
I didn't do anything out of the ordinary, I just added a new record and I got the error!!!!

**Comment by trey-wallis** [comment]
Did you just update to the lasted version of Obsidian?

This might be an issue that just surfaced, not sure.

**Comment by trey-wallis** [comment]
What was the error?

I am really sorry that this happened

**Comment by RoboG-11** [comment]
I have not updated Obisdian.
The only thing I did was to add a new row and I got the error. I didn't do anything "strange".
The information I had was very important...

**Comment by trey-wallis** [comment]
Sorry, I was on my phone. Looking back at this on desktop. What operating system are you using?

**Comment by trey-wallis** [comment]
Do you happen to have File History Feature enabled for windows?

**Comment by trey-wallis** [comment]
Btw it does look like Obsidian updated for you. 1.5.11 is the latest version

**Comment by RoboG-11** [comment]
I do not have this function enabled. I already tried to restore old versions of the .txt, but they do not exist.

**Comment by trey-wallis** [comment]
Okay. I'm thinking in this case the only thing that you can do would to try to use data forensics software to find pieces of the data that still exist. You could index your drive and search via keywords. However, it is possible that only part of the data exists. I have actually never done this but this is the only solution I found.

**Comment by trey-wallis** [comment]
Since the data is empty, the file was overwritten and that is actually harder to recovery than a file being deleted.

**Comment by RoboG-11** [comment]
Okay, I guess and there is no way to recover the data....

**Comment by trey-wallis** [comment]
I'm very sorry about that. I cannot guarantee that the plugin will work 100% of the time due to how updates come and make changes that are sometimes breaking.

I would recommend using the `Obsidian Local Backup` plugin from now on. That way you can always have a backup available

**Comment by RoboG-11** [comment]
Okay, don't worry. I understand what it's like to run a project alone. I will try to use the extension you recommend. Thanks
